#!/usr/bin/env python3
"""Generate typed Swift bridge files from codex TypeScript protocol unions."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


REQUEST_RESPONSE_OVERRIDES = {
    "account/login/start": "LoginAccountResponse",
    "account/login/cancel": "CancelLoginAccountResponse",
    "account/logout": "LogoutAccountResponse",
    "account/rateLimits/read": "GetAccountRateLimitsResponse",
    "app/list": "AppsListResponse",
    "config/mcpServer/reload": "McpServerRefreshResponse",
    "mcpServerStatus/list": "ListMcpServerStatusResponse",
}


def pascal(camel: str) -> str:
    return camel[0].upper() + camel[1:]


def candidate_names(base: str) -> list[str]:
    names = [base]
    if base.startswith("Fs"):
        names.append("FS" + base[2:])
    if base.startswith("Mcp"):
        names.append("MCP" + base[3:])
    return names


def resolve_swift_type(type_name: str, swift_types: set[str]) -> str | None:
    candidates: list[str] = []
    for raw_name in (type_name, f"CodexProtocolRoot{type_name}"):
        for candidate in candidate_names(raw_name):
            if candidate not in candidates:
                candidates.append(candidate)
    for candidate in candidates:
        if candidate in swift_types:
            return candidate
    return None


def collect_swift_types(swift_text: str) -> set[str]:
    pattern = re.compile(r"^(?:public\s+)?(?:struct|class|enum|typealias)\s+(\w+)", re.MULTILINE)
    return set(pattern.findall(swift_text))


def collect_method_cases(swift_text: str, enum_name: str) -> list[tuple[str, str]]:
    match = re.search(rf"enum {enum_name}[^{{]*\{{(.*?)\n\}}", swift_text, re.DOTALL)
    if not match:
        raise RuntimeError(f"{enum_name} enum not found in generated Swift")
    return re.findall(r'case\s+(\w+)\s*=\s*"([^"]+)"', match.group(1))


def parse_union_with_params(ts_text: str, union_name: str, has_id: bool) -> dict[str, str | None]:
    match = re.search(rf"export type {union_name}\s*=\s*(.*);", ts_text, re.DOTALL)
    if not match:
        raise RuntimeError(f"{union_name} union not found")
    if has_id:
        entries = re.findall(
            r'\{\s*"method":\s*"([^"]+)",\s*id:\s*[^,]+,\s*params:\s*([^,]+),\s*\}',
            match.group(1),
        )
    else:
        entries = re.findall(
            r'\{\s*"method":\s*"([^"]+)",\s*"params":\s*([^,}]+)\s*\}',
            match.group(1),
        )
    result: dict[str, str | None] = {}
    for method, params in entries:
        params = params.strip()
        result[method] = None if params == "undefined" else params
    return result


def infer_response_name(method: str, params_type_name: str | None) -> str:
    override = REQUEST_RESPONSE_OVERRIDES.get(method)
    if override is not None:
        return override
    if params_type_name and params_type_name.endswith("Params"):
        return f"{params_type_name[:-6]}Response"
    base = "".join(part[:1].upper() + part[1:] for part in re.split(r"[/_-]", method))
    return f"{base}Response"


def load_schema_definitions(path: Path) -> dict[str, object]:
    with path.open() as handle:
        return json.load(handle).get("definitions", {})


def is_empty_object_type(definitions: dict[str, object], type_name: str | None) -> bool:
    if type_name is None:
        return False
    candidates = [type_name, f"CodexProtocolRoot{type_name}"]
    for candidate in candidates:
        schema = definitions.get(candidate)
        if not isinstance(schema, dict):
            continue
        if schema.get("type") == "object" and not schema.get("properties") and not schema.get("required"):
            return True
    return False


def write_rpc_bridge(
    swift_text: str,
    client_request_ts: str,
    schema_definitions: dict[str, object],
    out_path: Path,
) -> None:
    swift_types = collect_swift_types(swift_text)
    methods = collect_method_cases(swift_text, "ClientRequestMethod")
    ts_mapping = parse_union_with_params(client_request_ts, "ClientRequest", has_id=True)

    lines = [
        "// GENERATED BY Scripts/generate-swift-bridge.py — DO NOT EDIT.",
        "",
        "import Foundation",
        "",
        "extension RPC {",
    ]

    for enum_case, wire_method in sorted(methods, key=lambda entry: pascal(entry[0])):
        params_type_name = ts_mapping.get(wire_method)
        if wire_method not in ts_mapping:
            raise RuntimeError(f"client request method {wire_method!r} missing from TS union")
        params_type = "EmptyParams" if params_type_name is None else resolve_swift_type(params_type_name, swift_types)
        if params_type is None and is_empty_object_type(schema_definitions, params_type_name):
            params_type = "EmptyParams"
        if params_type is None:
            raise RuntimeError(f"unable to resolve Swift params type for {wire_method!r}: {params_type_name}")
        response_type_name = infer_response_name(wire_method, params_type_name)
        response_type = resolve_swift_type(response_type_name, swift_types)
        if response_type is None and is_empty_object_type(schema_definitions, response_type_name):
            response_type = "EmptyResponse"
        if response_type is None:
            raise RuntimeError(
                f"unable to resolve Swift response type for {wire_method!r}: {response_type_name}"
            )
        lines.extend(
            [
                f"    public enum {pascal(enum_case)}: CodexRPCMethod {{",
                f"        public typealias Params = {params_type}",
                f"        public typealias Response = {response_type}",
                f"        public static let method = ClientRequestMethod.{enum_case}",
                "    }",
                "",
            ]
        )

    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    lines.append("")
    out_path.write_text("\n".join(lines))


def write_server_notifications(
    swift_text: str,
    server_notification_ts: str,
    schema_definitions: dict[str, object],
    out_path: Path,
) -> None:
    swift_types = collect_swift_types(swift_text)
    methods = collect_method_cases(swift_text, "NotificationMethod")
    ts_mapping = parse_union_with_params(server_notification_ts, "ServerNotification", has_id=False)

    entries: list[tuple[str, str, str]] = []
    for enum_case, wire_method in methods:
        if wire_method not in ts_mapping:
            raise RuntimeError(f"server notification {wire_method!r} missing from TS union")
        params_type_name = ts_mapping[wire_method]
        if params_type_name is None:
            raise RuntimeError(f"server notification {wire_method!r} unexpectedly has no params")
        params_type = resolve_swift_type(params_type_name, swift_types)
        if params_type is None and is_empty_object_type(schema_definitions, params_type_name):
            params_type = "EmptyResponse"
        if params_type is None:
            raise RuntimeError(f"unable to resolve Swift params type for {wire_method!r}: {params_type_name}")
        entries.append((enum_case, pascal(enum_case), params_type))

    lines = [
        "// GENERATED BY Scripts/generate-swift-bridge.py — DO NOT EDIT.",
        "",
        "import Foundation",
        "",
        "extension ServerNotifications {",
    ]

    for enum_case, base_name, params_type in entries:
        lines.extend(
            [
                f"    public enum {base_name}: CodexServerNotificationMethod {{",
                f"        public typealias Params = {params_type}",
                f"        public static let method = NotificationMethod.{enum_case}",
                "    }",
                "",
            ]
        )

    lines.extend(
        [
            "}",
            "",
            "public enum ServerNotificationEvent: Sendable {",
        ]
    )

    for enum_case, _, params_type in entries:
        lines.append(f"    case {enum_case}({params_type})")

    lines.extend(
        [
            "",
            "    public var method: NotificationMethod {",
            "        switch self {",
        ]
    )

    for enum_case, _, _ in entries:
        lines.append(f"        case .{enum_case}: return .{enum_case}")

    lines.extend(
        [
            "        }",
            "    }",
            "",
            "    public init(from data: Data) throws {",
            "        try self.init(from: data, decoder: newJSONDecoder())",
            "    }",
            "",
            "    public init(from data: Data, decoder: JSONDecoder) throws {",
            "        let envelope = try decoder.decode(_ServerNotificationEnvelope.self, from: data)",
            "        switch envelope.method {",
        ]
    )

    for enum_case, _, params_type in entries:
        lines.extend(
            [
                f"        case .{enum_case}:",
                f"            self = .{enum_case}(try decoder.decode(_ServerNotificationPayload<{params_type}>.self, from: data).params)",
            ]
        )

    lines.extend(
        [
            "        }",
            "    }",
            "}",
            "",
            "private struct _ServerNotificationEnvelope: Decodable {",
            "    let method: NotificationMethod",
            "}",
            "",
            "private struct _ServerNotificationPayload<Params: Decodable>: Decodable {",
            "    let params: Params",
            "}",
            "",
        ]
    )

    out_path.write_text("\n".join(lines))


def write_server_requests(
    swift_text: str,
    server_request_ts: str,
    schema_definitions: dict[str, object],
    out_path: Path,
) -> None:
    swift_types = collect_swift_types(swift_text)
    methods = collect_method_cases(swift_text, "ServerRequestMethod")
    ts_mapping = parse_union_with_params(server_request_ts, "ServerRequest", has_id=True)

    entries: list[tuple[str, str, str, str]] = []
    for enum_case, wire_method in methods:
        if wire_method not in ts_mapping:
            raise RuntimeError(f"server request {wire_method!r} missing from TS union")
        params_type_name = ts_mapping[wire_method]
        if params_type_name is None:
            raise RuntimeError(f"server request {wire_method!r} unexpectedly has no params")
        params_type = resolve_swift_type(params_type_name, swift_types)
        if params_type is None and is_empty_object_type(schema_definitions, params_type_name):
            params_type = "EmptyParams"
        if params_type is None:
            raise RuntimeError(f"unable to resolve Swift params type for {wire_method!r}: {params_type_name}")
        response_type_name = infer_response_name(wire_method, params_type_name)
        response_type = resolve_swift_type(response_type_name, swift_types)
        if response_type is None and is_empty_object_type(schema_definitions, response_type_name):
            response_type = "EmptyResponse"
        if response_type is None:
            raise RuntimeError(
                f"unable to resolve Swift response type for {wire_method!r}: {response_type_name}"
            )
        entries.append((enum_case, pascal(enum_case), params_type, response_type))

    lines = [
        "// GENERATED BY Scripts/generate-swift-bridge.py — DO NOT EDIT.",
        "",
        "import Foundation",
        "",
        "extension ServerRequests {",
    ]

    for enum_case, base_name, params_type, response_type in entries:
        lines.extend(
            [
                f"    public enum {base_name}: CodexServerRequestMethod {{",
                f"        public typealias Params = {params_type}",
                f"        public typealias Response = {response_type}",
                f"        public static let method = ServerRequestMethod.{enum_case}",
                "    }",
                "",
            ]
        )

    lines.extend(
        [
            "}",
            "",
            "public enum AnyTypedServerRequest: Sendable {",
        ]
    )

    for enum_case, _, _, _ in entries:
        lines.append(f"    case {enum_case}(TypedServerRequest<ServerRequests.{pascal(enum_case)}>)")

    lines.extend(
        [
            "",
            "    public var id: RequestId {",
            "        switch self {",
        ]
    )

    for enum_case, _, _, _ in entries:
        lines.append(f"        case .{enum_case}(let request): return request.id")

    lines.extend(
        [
            "        }",
            "    }",
            "",
            "    public var method: ServerRequestMethod {",
            "        switch self {",
        ]
    )

    for enum_case, _, _, _ in entries:
        lines.append(f"        case .{enum_case}: return .{enum_case}")

    lines.extend(
        [
            "        }",
            "    }",
            "",
            "    public init(from data: Data) throws {",
            "        try self.init(from: data, decoder: newJSONDecoder())",
            "    }",
            "",
            "    public init(from data: Data, decoder: JSONDecoder) throws {",
            "        let envelope = try decoder.decode(_ServerRequestEnvelope.self, from: data)",
            "        switch envelope.method {",
        ]
    )

    for enum_case, _, params_type, _ in entries:
        lines.extend(
            [
                f"        case .{enum_case}:",
                f"            let payload = try decoder.decode(_ServerRequestPayload<{params_type}>.self, from: data)",
                f"            self = .{enum_case}(TypedServerRequest<ServerRequests.{pascal(enum_case)}>(id: payload.id, params: payload.params))",
            ]
        )

    lines.extend(
        [
            "        }",
            "    }",
            "}",
            "",
            "private struct _ServerRequestEnvelope: Decodable {",
            "    let method: ServerRequestMethod",
            "}",
            "",
            "private struct _ServerRequestPayload<Params: Decodable>: Decodable {",
            "    let id: RequestId",
            "    let params: Params",
            "}",
            "",
        ]
    )

    out_path.write_text("\n".join(lines))


def write_metadata(out_path: Path, codex_version: str) -> None:
    out_path.write_text(
        "\n".join(
            [
                "// GENERATED BY Scripts/generate-swift-bridge.py — DO NOT EDIT.",
                "",
                "import Foundation",
                "",
                "public enum CodexBindingMetadata {",
                f'    public static let codexVersion = "{codex_version}"',
                "    public static let includesExperimentalAPI = true",
                "}",
                "",
            ]
        )
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--swift", required=True, type=Path)
    parser.add_argument("--client-request-ts", required=True, type=Path)
    parser.add_argument("--server-notification-ts", required=True, type=Path)
    parser.add_argument("--server-request-ts", required=True, type=Path)
    parser.add_argument("--schema", required=True, type=Path)
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument("--codex-version", required=True)
    return parser


def main() -> int:
    args = build_parser().parse_args()

    swift_text = args.swift.read_text()
    client_request_ts = args.client_request_ts.read_text()
    server_notification_ts = args.server_notification_ts.read_text()
    server_request_ts = args.server_request_ts.read_text()
    schema_definitions = load_schema_definitions(args.schema)

    args.out_dir.mkdir(parents=True, exist_ok=True)

    write_rpc_bridge(
        swift_text,
        client_request_ts,
        schema_definitions,
        args.out_dir / "CodexRPCMethodsGenerated.swift",
    )
    write_server_notifications(
        swift_text,
        server_notification_ts,
        schema_definitions,
        args.out_dir / "CodexServerNotificationsGenerated.swift",
    )
    write_server_requests(
        swift_text,
        server_request_ts,
        schema_definitions,
        args.out_dir / "CodexServerRequestsGenerated.swift",
    )
    write_metadata(args.out_dir / "CodexBindingMetadataGenerated.swift", args.codex_version)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
